#
# This file is part of the CMaNGOS Project. See AUTHORS file for Copyright information
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

language: cpp

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# make use of the new container based infrastructure at travis to improve performance (we don't need sudo)
sudo: false

# only run travis on the master branch
branches:
  only:
    - master

os:
  - linux

compiler:
  - clang
  - gcc

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Release PCH_FLAG="ON"

addons:
  apt:
    sources:
      - kubuntu-backports
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libtool
      - gcc-4.8
      - g++-4.8
      - make
      - cmake
      - libboost1.55-dev
      - libboost-system1.55-dev
      - libboost-program-options1.55-dev
      - libboost-thread1.55-dev
  
# overwrite GCC version for GCC build only
before_install:
  - if [ $CC = "gcc" ] ; then export CC=gcc-4.8 CXX=g++-4.8 ; fi

script:
  - test -d _build || mkdir _build
  - test -d _install || mkdir _install
  - cd _build
  - if [ $PCH_FLAG = "ON" ] ; then
        cmake -DCMAKE_INSTALL_PREFIX=../_install .. -DPCH=1;
    else
        cmake -DCMAKE_INSTALL_PREFIX=../_install ..;
    fi
  - make -j4

# if this configuration file is not in one of the offical CMaNGOS repositories at http://github.com/cmangos/, PLEASE remove the notifications or point them to another IRC channel!

