#
# This file is part of the CMaNGOS Project. See AUTHORS file for Copyright information
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

language: cpp

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# only run travis on the master branch
# branches:
#   only:
#     - master

compiler:
  - gcc
  - clang

before_install:
  # update compiling tools for c++11 support
  - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90

script:
  - test -d _build || mkdir _build
  - test -d _install || mkdir _install
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=../_install ..
  - make -j4
